version: '3.4'

services:
  db:
    image: restaspenet5-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemay
    ports:
      - 3308:3306
    networks:
      - udemy-network

  restaspenet5:
    image: restaspenet5
    build:
      context: .
      dockerfile: RestAspeNet5/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44301:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge
